REPO_UI_URL = "https://github.com/microsoft/vscode"
REPO_API_BASE = "https://api.github.com/repos"
REACT_REPO = "facebook/react"
NONEXISTENT_REPO = "microsoft/nonexistent-repo-12345"
LOG_FILE = "logs/tests.log"